import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Activity, ArrowRight, ArrowUpRight, Bell, BookOpen, BrainCircuit, CalendarDays, Check, ChevronRight, Clock3, Compass, Database, Flame, GraduationCap, LockKeyhole, Moon, Network, Sparkles, Sun, Target, TrendingUp, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Badge, Button, Card, ChartCard, EmptyState, Modal, PageTitle, ProgressBar, SectionTitle, Tabs } from '../components/ui';
import { TopicCard } from '../components/domain';
import { MasteryChart, QuizPerformanceChart, SubjectPerformanceChart, WeeklyStudyChart } from '../components/Charts';
import { demoStudent, initialTasks, subjects, topics } from '../data/mockData';
import { useApp } from '../context/AppContext';
import { plannerService } from '../services/plannerService';
import { progressService } from '../services/progressService';
import type { StudyTask, Topic } from '../types';

function SubjectMasteryCard({ subject, index }: { subject: (typeof subjects)[number]; index: number }) {
  return <motion.div className="subject-mastery-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }}><div className={`subject-icon subject-${subject.accent}`}>{subject.icon === 'BrainCircuit' ? <BrainCircuit size={17} /> : subject.icon === 'Database' ? <Database size={17} /> : subject.icon === 'Network' ? <Network size={17} /> : <Activity size={17} />}</div><div className="subject-mastery-main"><div><strong>{subject.name}</strong><span>{subject.mastery}%</span></div><ProgressBar value={subject.mastery} tone={subject.mastery < 60 ? 'warning' : subject.mastery > 80 ? 'success' : 'accent'} /></div></motion.div>;
}

export function DashboardPage() {
  const { student } = useApp();
  const navigate = useNavigate();
  const [tasks, setTasks] = useState<StudyTask[]>(initialTasks);
  const [insight, setInsight] = useState('Your Database Systems performance improved 14% this week. Your biggest remaining gap is normalization.');
  useEffect(() => { plannerService.list().then(setTasks).catch(() => undefined); progressService.overview().then((result) => setInsight(result.insight)).catch(() => undefined); }, []);
  const firstName = student.name.split(' ')[0] || 'Alex';
  const nextTasks = [...tasks].sort((a, b) => a.time.localeCompare(b.time)).slice(0, 4);
  return <div className="dashboard-page page-content">
    <PageTitle eyebrow="MONDAY, SEPTEMBER 30, 2026" title={`Good morning, ${firstName}.`} description="Here's what deserves your attention today." action={<Button variant="secondary" icon={<CalendarDays size={15} />} onClick={() => navigate('/planner')}>View study plan</Button>} />
    <section className="dashboard-hero-grid">
      <Card className="next-best-card"><div className="next-best-glow" /><div className="next-best-content"><div className="next-card-meta"><span className="next-card-icon"><Sparkles size={15} /></span><span>YOUR NEXT BEST ACTION</span><Badge tone="accent">Picked for you</Badge></div><h2>K-Nearest Neighbors</h2><p>You struggled with distance metrics in your last quiz. A short, focused review will make the next practice set count.</p><div className="next-card-bottom"><div className="next-card-time"><Clock3 size={14} /><span>20 min recommended</span><i /><span>51% mastery</span></div><Button onClick={() => navigate('/tutor/knn-guided')}>Start learning <ArrowRight size={15} /></Button></div></div><div className="next-mastery-orbit"><div className="mastery-orbit-ring"><span>51<small>%</small></span></div><small>topic mastery</small><span className="orbit-caption"><ArrowUpRight size={12} /> room to grow</span></div></Card>
      <Card className="streak-card"><div className="streak-card-top"><span className="streak-icon"><Flame size={18} /></span><span className="streak-menu">THIS WEEK</span></div><strong className="streak-count">7 <small>days</small></strong><p>Your longest streak this month. Keep the rhythm light and steady.</p><div className="streak-dots" aria-label="Five of seven days completed this week">{['M','T','W','T','F','S','S'].map((day,index)=><span key={`${day}-${index}`} className={index < 5 ? 'done' : ''}><i>{index < 5 ? <Check size={11} /> : day}</i><small>{day}</small></span>)}</div><Link to="/progress" className="small-link">View consistency <ArrowRight size={13} /></Link></Card>
    </section>

    <div className="dashboard-grid-two"><section className="dashboard-section"><SectionTitle title="Mastery overview" description="A quick pulse across your courses." action={<Link to="/knowledge" className="small-link">Knowledge map <ArrowRight size={13} /></Link>} /><div className="mastery-list">{subjects.map((subject,index)=><SubjectMasteryCard key={subject.id} subject={subject} index={index} />)}</div></section>
    <section className="dashboard-section weak-section"><SectionTitle title="Worth a second look" description="A little focused practice goes a long way." action={<Link to="/knowledge" className="small-link">See all <ArrowRight size={13} /></Link>} /><div className="weak-topic-list">{topics.filter((topic) => topic.band === 'weak').slice(0,3).map((topic,index)=><div className="weak-topic-row" key={topic.id}><span className={`weak-dot weak-dot-${index}`} /><span className="weak-topic-name"><strong>{topic.name === 'K-Nearest Neighbors' ? 'KNN' : topic.name}</strong><small>{topic.subjectId === 'ml' ? 'Machine Learning' : topic.subjectId === 'db' ? 'Database Systems' : 'Statistics'}</small></span><strong className="weak-percent">{topic.mastery}%</strong><Button size="sm" variant="soft" onClick={() => navigate(topic.id === 'knn' ? '/tutor/knn-guided' : '/quiz')}>Practice</Button></div>)}</div></section></div>

    <div className="dashboard-grid-two lower-dashboard-grid"><section className="dashboard-section"><SectionTitle title="Today's plan" description="A little progress, one session at a time." action={<Link to="/planner" className="small-link">Open planner <ArrowRight size={13} /></Link>} /><Card className="today-plan-card">{nextTasks.map((task,index)=><div className={`timeline-row ${task.completed ? 'completed' : ''}`} key={task.id}><div className="timeline-time">{task.time}</div><div className="timeline-rail"><i className={index === 0 ? 'current' : ''} />{index < nextTasks.length - 1 && <span />}</div><div className="timeline-copy"><strong>{task.title}</strong><small>{task.subject} <i /> {task.duration} min</small></div><span className="timeline-status">{task.completed ? <Badge tone="success">Done</Badge> : <button className="icon-button" aria-label={`Open ${task.title}`} onClick={() => navigate('/planner')}><ChevronRight size={15} /></button>}</span></div>)}</Card></section>
    <section className="dashboard-section"><SectionTitle title="Your week, in focus" description="Time you invested in learning." action={<Link to="/progress" className="small-link">Details <ArrowRight size={13} /></Link>} /><Card className="weekly-chart-card"><div className="chart-stat"><span><strong>11.2</strong> hrs</span><Badge tone="success"><TrendingUp size={12} /> 18% vs last week</Badge></div><WeeklyStudyChart compact /></Card></section></div>

    <Card className="ai-insight-card"><span className="insight-icon"><Sparkles size={17} /></span><div className="insight-copy"><span className="eyebrow">A NOTE FROM YOUR COPILOT</span><p>{insight}</p></div><Button variant="ghost" onClick={() => navigate('/knowledge')}>Explore the gap <ArrowRight size={14} /></Button></Card>
  </div>;
}

export function KnowledgePage() {
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<Topic | null>(null);
  const navigate = useNavigate();
  const filters = ['All', 'Strong', 'Needs Review', 'Weak'];
  const filteredTopics = topics.filter((topic) => filter === 'All' || filter === 'Strong' && topic.band === 'strong' || filter === 'Weak' && topic.band === 'weak' || filter === 'Needs Review' && topic.band !== 'strong');
  const grouped = useMemo(() => subjects.map((subject) => ({ subject, items: filteredTopics.filter((topic) => topic.subjectId === subject.id) })).filter((group) => group.items.length), [filteredTopics]);
  const subjectName = (id: string) => subjects.find((subject) => subject.id === id)?.name ?? 'Course topic';
  return <div className="page-content"><PageTitle eyebrow="YOUR LEARNING, MADE VISIBLE" title="Your Knowledge Map" description="A clearer picture of what’s sticking—and what deserves another look." action={<Button variant="secondary" icon={<BrainCircuit size={15} />} onClick={() => navigate('/quiz')}>Check my understanding</Button>} />
    <Tabs className="filter-tabs" label="Filter topics by mastery" value={filter} onChange={setFilter} items={filters.map((item) => ({ value: item, label: item, count: item === 'Weak' ? topics.filter((topic) => topic.band === 'weak').length : undefined }))} />
    <div className="knowledge-overview"><span className="knowledge-overview-icon"><Compass size={18} /></span><div><strong>69% overall mastery</strong><small>Across 4 active subjects · up 6% this month</small></div><div className="knowledge-overview-progress"><ProgressBar value={69} /></div><Link to="/progress" className="small-link">See progress <ArrowRight size={13} /></Link></div>
    <div className="knowledge-subjects">{grouped.map(({ subject, items })=><section className="knowledge-subject" key={subject.id}><div className="knowledge-subject-heading"><div className={`subject-icon subject-${subject.accent}`}>{subject.icon === 'BrainCircuit' ? <BrainCircuit size={17} /> : subject.icon === 'Database' ? <Database size={17} /> : subject.icon === 'Network' ? <Network size={17} /> : <Activity size={17} />}</div><div><h2>{subject.name}</h2><small>{items.length} topics · {subject.mastery}% overall mastery</small></div><Link to="/quiz" className="small-link">Practice course <ArrowRight size={13} /></Link></div><div className="topic-card-grid">{items.map((topic) => <TopicCard key={topic.id} topic={topic} onSelect={setSelected} />)}</div></section>)}</div>
    {!filteredTopics.length && <EmptyState icon={<Compass size={21} />} title="Nothing in this view yet" description="Try another mastery filter to see more topics." />}
    <Modal open={selected !== null} onClose={() => setSelected(null)} title={selected?.name ?? 'Topic detail'} description={selected ? subjectName(selected.subjectId) : undefined}>
      {selected && <div className="topic-detail"><div className="topic-detail-mastery"><div><span className="eyebrow">CURRENT MASTERY</span><strong>{selected.mastery}<small>%</small></strong></div><ProgressBar value={selected.mastery} tone={selected.band === 'weak' ? 'warning' : selected.band === 'strong' ? 'success' : 'blue'} /></div><div className="topic-detail-grid"><div><span>Recent quiz</span><strong>{selected.recentScore}%</strong></div><div><span>Last studied</span><strong>{selected.lastStudied}</strong></div></div><div className="topic-recommendation"><Sparkles size={15} /><span><small>RECOMMENDED NEXT</small><strong>{selected.recommendation}</strong></span></div><Button onClick={() => { setSelected(null); navigate(selected.id === 'knn' ? '/tutor/knn-guided' : '/quiz'); }}>Start a focused session <ArrowRight size={15} /></Button></div>}
    </Modal>
  </div>;
}

function MetricCard({ label, value, suffix, delta, icon, accent }: { label: string; value: string; suffix?: string; delta: string; icon: React.ReactNode; accent: string }) {
  return <Card className="metric-card"><div className={`metric-icon metric-${accent}`}>{icon}</div><span className="metric-label">{label}</span><div className="metric-value">{value}<small>{suffix}</small></div><span className="metric-delta"><TrendingUp size={12} /> {delta}</span></Card>;
}

export function ProgressPage() {
  const [view, setView] = useState<'week' | 'month'>('week');
  const [summary, setSummary] = useState<{ overallMastery: number; weeklyHours: number; quizAccuracy: number; currentStreak: number; improvement: number } | null>(null);
  useEffect(() => { progressService.overview().then(setSummary).catch(() => setSummary(null)); }, []);
  return <div className="page-content"><PageTitle eyebrow="YOUR PROGRESS, OVER TIME" title="Look how far you’ve come." description="Understanding grows through small, steady sessions. Here’s the shape of yours." action={<div className="segmented-control"><button className={view === 'week' ? 'active' : ''} onClick={() => setView('week')}>This week</button><button className={view === 'month' ? 'active' : ''} onClick={() => setView('month')}>This month</button></div>} />
    <div className="metric-grid-four"><MetricCard label="Overall mastery" value={`${summary?.overallMastery ?? 69}`} suffix="%" delta={`+${view === 'week' ? 6 : summary?.improvement ?? 18}% this ${view}`} icon={<Target size={18} />} accent="violet" /><MetricCard label="Study time" value={`${summary?.weeklyHours ?? 11.2}`} suffix="hrs" delta="+2.4 hrs vs prior" icon={<Clock3 size={18} />} accent="blue" /><MetricCard label="Quiz accuracy" value={`${summary?.quizAccuracy ?? 78}`} suffix="%" delta="+9% this month" icon={<BrainCircuit size={18} />} accent="teal" /><MetricCard label="Current streak" value={`${summary?.currentStreak ?? 7}`} suffix="days" delta="Personal best: 12" icon={<Flame size={18} />} accent="amber" /></div>
    <div className="progress-chart-grid"><section className="dashboard-section"><SectionTitle title="Mastery over time" description="Confidence grows with each focused session." /><ChartCard title="Topic mastery" badge={<Badge tone="success"><TrendingUp size={12} /> +18% this month</Badge>}><MasteryChart /></ChartCard></section><section className="dashboard-section"><SectionTitle title="Study hours" description="A balanced rhythm, week by week." /><ChartCard title="Hours learned" badge={<Badge tone="neutral">11.2 hrs</Badge>}><WeeklyStudyChart /></ChartCard></section></div>
    <div className="progress-chart-grid"><section className="dashboard-section"><SectionTitle title="Quiz performance" description="Recall is getting stronger." /><ChartCard title="Accuracy trend" badge={<Badge tone="success">78% average</Badge>}><QuizPerformanceChart /></ChartCard></section><section className="dashboard-section"><SectionTitle title="Subject performance" description="A view across your active courses." /><ChartCard title="Course mastery" badge={<Badge tone="neutral">4 subjects</Badge>}><SubjectPerformanceChart data={subjects} /></ChartCard></section></div>
    <div className="dashboard-grid-two topic-performance-grid"><Card className="topic-performance-card"><SectionTitle title="Strongest topics" description="Knowledge that’s sticking well." /><div className="topic-performance-list">{topics.filter((topic) => topic.band === 'strong').slice(0,4).map((topic) => <div key={topic.id}><span className="performance-check"><Check size={13} /></span><span>{topic.name}</span><strong>{topic.mastery}%</strong></div>)}</div></Card><Card className="topic-performance-card"><SectionTitle title="Topics to revisit" description="Your next opportunities to grow." /><div className="topic-performance-list">{topics.filter((topic) => topic.band === 'weak').slice(0,4).map((topic) => <div key={topic.id}><span className="performance-review"><ArrowUpRight size={13} /></span><span>{topic.name}</span><strong>{topic.mastery}%</strong></div>)}</div></Card></div>
  </div>;
}

export function SettingsPage() {
  const { theme, setTheme, toast, student, setStudent } = useApp();
  const [notifications, setNotifications] = useState(true);
  const [weeklyDigest, setWeeklyDigest] = useState(true);
  const [guidedMode, setGuidedMode] = useState(true);
  const themeOptions = [{ value: 'light', label: 'Light', copy: 'A bright, focused workspace', icon: Sun }, { value: 'dark', label: 'Dark', copy: 'Easy on the eyes after hours', icon: Moon }, { value: 'system', label: 'System', copy: 'Follow your device preference', icon: Activity }] as const;
  const saveNotice = () => toast('Preferences saved', 'Your study space has been updated.');
  const toggle = (label: string, value: boolean, setter: (next: boolean) => void) => <button type="button" className={`switch ${value ? 'on' : ''}`} role="switch" aria-checked={value} aria-label={label} onClick={() => setter(!value)}><span /></button>;
  return <div className="page-content"><PageTitle eyebrow="MAKE CAMPUSAI YOURS" title="Settings" description="Shape a study space that works the way you do." />
    <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{[{ label: 'Profile', icon: UserRound },{ label: 'Appearance', icon: Sun },{ label: 'Notifications', icon: Bell },{ label: 'Study preferences', icon: BookOpen },{ label: 'AI preferences', icon: Sparkles },{ label: 'Privacy', icon: LockKeyhole },{ label: 'Account', icon: GraduationCap }].map(({label,icon:Icon},index)=><a key={label} href={`#settings-${index}`} className={index===0?'active':''}><Icon size={15} />{label}</a>)}</nav>
    <div className="settings-panels"><Card id="settings-0" className="settings-panel"><div className="settings-panel-heading"><div><h2>Profile</h2><p>Your student details and academic context.</p></div><Link to="/profile" className="small-link">View profile <ArrowRight size={13} /></Link></div><div className="settings-profile-row"><span className="avatar avatar-large">{student.name.split(' ').map((part) => part[0]).join('').slice(0,2)}</span><div><strong>{student.name}</strong><span>{student.email}</span><small>{student.university} · {student.course}</small></div><button className="btn btn-secondary btn-sm" onClick={saveNotice}>Edit profile</button></div></Card>
    <Card id="settings-1" className="settings-panel"><div className="settings-panel-heading"><div><h2>Appearance</h2><p>Choose the theme that feels right for your study space.</p></div></div><div className="theme-choice-grid">{themeOptions.map(({value,label,copy,icon:Icon})=><button type="button" key={value} onClick={() => { setTheme(value); toast('Theme updated', `${label} appearance is now active.`); }} className={`theme-choice ${theme === value ? 'selected' : ''}`} aria-pressed={theme===value}><span className="theme-choice-icon"><Icon size={17} /></span><strong>{label}</strong><small>{copy}</small>{theme===value && <span className="theme-choice-check"><Check size={12} /></span>}</button>)}</div><div className="settings-row"><div><strong>Accent color</strong><span>Campus indigo is the signature color for this workspace.</span></div><span className="accent-swatch"><i /> Indigo</span></div></Card>
    <Card id="settings-2" className="settings-panel"><div className="settings-panel-heading"><div><h2>Notifications</h2><p>Get gentle reminders that support your routine.</p></div></div><div className="settings-row"><div><strong>Study reminders</strong><span>A nudge when a planned study session is coming up.</span></div>{toggle('Study reminders',notifications,(next)=>{setNotifications(next);saveNotice();})}</div><div className="settings-row"><div><strong>Weekly learning summary</strong><span>A quick look at your progress every Sunday.</span></div>{toggle('Weekly learning summary',weeklyDigest,(next)=>{setWeeklyDigest(next);saveNotice();})}</div></Card>
    <Card id="settings-3" className="settings-panel"><div className="settings-panel-heading"><div><h2>Study preferences</h2><p>Keep your plan realistic and focused.</p></div></div><div className="settings-row"><div><strong>Daily study goal</strong><span>Minutes of focused learning per day.</span></div><div className="inline-select"><select aria-label="Daily study goal" value={student.dailyGoalMinutes} onChange={(event)=>setStudent({...student,dailyGoalMinutes:Number(event.target.value)})}><option value="30">30 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option><option value="120">2 hours</option></select></div></div></Card>
    <Card id="settings-4" className="settings-panel"><div className="settings-panel-heading"><div><h2>AI preferences</h2><p>Choose how CampusAI supports your learning.</p></div></div><div className="settings-row"><div><strong>Guided learning mode</strong><span>Ask a question and reason it through step by step.</span></div>{toggle('Guided learning mode',guidedMode,(next)=>{setGuidedMode(next);saveNotice();})}</div><div className="settings-row"><div><strong>Answer style</strong><span>Clear explanations with examples by default.</span></div><span className="settings-pill">Clear & concise <ChevronRight size={13} /></span></div></Card>
    <Card id="settings-5" className="settings-panel"><div className="settings-panel-heading"><div><h2>Privacy</h2><p>Your data stays in this browser-only product demo.</p></div></div><div className="privacy-note"><LockKeyhole size={17} /><span><strong>No real AI, account or cloud upload is connected.</strong><small>Demo state is kept in localStorage on this device. Don’t enter real credentials or sensitive student information.</small></span></div></Card>
    <Card id="settings-6" className="settings-panel"><div className="settings-panel-heading"><div><h2>Account</h2><p>Manage this local demo profile.</p></div></div><button className="settings-row settings-button-row" onClick={()=>{localStorage.removeItem('campusai.student.v1');setStudent(demoStudent);toast('Demo profile restored','Your workspace is back to Alex Morgan.');}}><div><strong>Restore demo profile</strong><span>Return to the default CampusAI sample student.</span></div><span className="settings-pill">Reset <ChevronRight size={13} /></span></button></Card>
    </div></div>
  </div>;
}

export function ProfilePage() {
  const { student } = useApp();
  const statItems = [{ icon: Flame, value: '7 days', label: 'Study streak' }, { icon: Clock3, value: '48.5 hrs', label: 'Hours studied' }, { icon: BrainCircuit, value: '24', label: 'Quizzes completed' }, { icon: Check, value: '18', label: 'Topics mastered' }];
  return <div className="page-content"><PageTitle eyebrow="YOUR LEARNING PROFILE" title="A little about you." description="Your CampusAI workspace, shaped around your academic journey." />
    <Card className="profile-hero-card"><div className="profile-hero-orb" /><div className="profile-identity"><span className="avatar avatar-profile">{student.name.split(' ').map((part)=>part[0]).join('').slice(0,2)}</span><div><Badge tone="accent">Student workspace</Badge><h2>{student.name}</h2><p>{student.email}</p></div></div><div className="profile-academics"><div><GraduationCap size={16} /><span><small>UNIVERSITY</small><strong>{student.university}</strong></span></div><div><BookOpen size={16} /><span><small>COURSE</small><strong>{student.course}</strong></span></div><div><CalendarDays size={16} /><span><small>SEMESTER</small><strong>{student.semester}</strong></span></div></div><Link to="/settings" className="profile-edit-link">Edit profile <ArrowRight size={14} /></Link></Card>
    <div className="metric-grid-four profile-stats-grid">{statItems.map(({icon:Icon,value,label})=><Card className="profile-stat-card" key={label}><span className="profile-stat-icon"><Icon size={18} /></span><strong>{value}</strong><span>{label}</span></Card>)}</div>
    <div className="dashboard-grid-two"><Card className="profile-course-card"><SectionTitle title="Your courses" description="The subjects you’re learning right now." /><div className="profile-course-list">{subjects.map((subject)=><div key={subject.id}><span className={`subject-icon subject-${subject.accent}`}>{subject.icon==='BrainCircuit'?<BrainCircuit size={16}/>:subject.icon==='Database'?<Database size={16}/>:subject.icon==='Network'?<Network size={16}/>:<Activity size={16}/>}</span><span>{subject.name}</span><strong>{subject.mastery}%</strong><ProgressBar value={subject.mastery} tone={subject.mastery>80?'success':subject.mastery<60?'warning':'accent'} /></div>)}</div><Link to="/knowledge" className="small-link">Open knowledge map <ArrowRight size={13} /></Link></Card><Card className="profile-journey-card"><span className="profile-journey-icon"><Sparkles size={18} /></span><div className="eyebrow">YOUR LEARNING RHYTHM</div><h3>Small steps add up.</h3><p>You’ve kept a 7-day streak and invested 48.5 hours this term. Keep showing up for one clear next step.</p><Link to="/progress" className="btn btn-secondary btn-sm">Explore your progress <ArrowRight size={13} /></Link></Card></div>
  </div>;
}
